# Generated by Django 2.1.2 on 2019-04-20 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 4, 20, 16, 1, 20, 803402, tzinfo=utc))),
            ],
        ),
    ]
