# Generated by Django 2.1.2 on 2019-04-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doto', '0002_auto_20190420_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='cross',
            field=models.BooleanField(default=False),
        ),
    ]
